# server配置
server:
  port: 8080
  servlet:
    context-path: /

#--------------------------------------------------------------

fabric:
  mspId: Org1MSP
  channel: businesschannel
  certificatePath: D:/Mine/Blockchain/Z/1orderer1org2peer/Chaincode/new/safyfood/safyfood/src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  privateKeyPath: D:/Mine/Blockchain/Z/1orderer1org2peer/Chaincode/new/safyfood/safyfood/src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk
  tlsCertPath: D:/Mine/Blockchain/Z/1orderer1org2peer/Chaincode/new/safyfood/safyfood/src/main/resources/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/ca.crt

logging:
  level:
    org:
      hyperledger: trace
# 连接池配置

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///safyfooddb
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: foot_safety_Chaincode_JavaClient
# mybatis-plus的配置
  #配置Redis连接参数 /这里需要配合虚拟机的redis服务。存放验证码信息
  data:
    redis:
      host: 192.168.10.101
      port: 6379
      database: 0


mybatis-plus:
  type-aliases-package: com.system.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
#      table-prefix: news_ # 设置表的前缀
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt配置


jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: training_system123456  #当前程序签名秘钥 自定义

#access-key-id 和 access-key-secret 是敏感信息 上传到 git 会报错
#添加了假数据 需要使用时候删掉_Sensitive_Information
aliyun:
  sms:
    access-key-id: LTAI5tNkSSJ7QRvpX2RtWDDF_Sensitive_Information
    access-key-secret: 5OccOCTSSs4RRgBZ8cDLVL9XPAZ4Rj_Sensitive_Information
    endpoint: dysmsapi.aliyuncs.com

